# permissions to do viewer toobigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: toobig-viewer-role
rules:
- apiGroups:
  - bar.foo
  resources:
  - toobigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bar.foo
  resources:
  - toobigs/status
  verbs:
  - get
