# permissions to do edit toobigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: toobig-editor-role
rules:
- apiGroups:
  - bar.foo
  resources:
  - toobigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bar.foo
  resources:
  - toobigs/status
  verbs:
  - get
  - patch
  - update
